# Generated by Django 5.0.6 on 2024-06-25 07:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("universe", "0002_answer_useranswer_answer"),
    ]

    operations = [
        migrations.AddField(
            model_name="answer",
            name="question",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="answers",
                to="universe.question",
            ),
            preserve_default=False,
        ),
    ]
