# Generated by Django 5.0.6 on 2024-06-26 10:20

import universe.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("universe", "0003_alphabet_image_upload_alter_alphabet_audio_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alphabet",
            name="audio_file",
            field=models.FileField(
                upload_to=universe.models.upload_alphabet_audio_file
            ),
        ),
    ]
