# Generated by Django 5.0.6 on 2024-06-25 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("universe", "0003_answer_question"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="question",
            name="is_correct",
        ),
        migrations.AddField(
            model_name="answer",
            name="is_correct",
            field=models.BooleanField(default=False),
        ),
    ]
