# Generated by Django 5.0.6 on 2024-06-25 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("universe", "0005_question_planet"),
    ]

    operations = [
        migrations.AddField(
            model_name="answer",
            name="planet",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="universe.planet",
            ),
            preserve_default=False,
        ),
    ]
